# Generated by Django 5.2.7 on 2025-10-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo_institucional', models.EmailField(max_length=120)),
                ('carrera_egreso', models.CharField(max_length=150)),
                ('carreras_imparte', models.CharField(blank=True, max_length=255, null=True)),
                ('grado_academico', models.CharField(blank=True, choices=[('Licenciatura', 'Licenciatura'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado'), ('Especialización', 'Especialización')], max_length=100, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('logros', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'docentes',
            },
        ),
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo_institucional', models.EmailField(max_length=100)),
                ('carrera_egreso', models.CharField(max_length=150)),
                ('anio_egreso', models.IntegerField()),
                ('ocupacion_actual', models.CharField(blank=True, max_length=150, null=True)),
                ('perfil_linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('puesto', models.CharField(blank=True, max_length=150, null=True)),
                ('logros', models.TextField(blank=True, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('competencias', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'egresados',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo_institucional', models.EmailField(max_length=120)),
                ('numero_control', models.CharField(max_length=50)),
                ('carrera_actual', models.CharField(max_length=150)),
                ('otra_carrera', models.CharField(default='No', max_length=150)),
                ('semestre', models.CharField(blank=True, max_length=20, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('area_interes', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'estudiantes',
            },
        ),
    ]
